### ISSUE TITLE
Unable to complete configuration

### ISSUE THREAD

**Issue by sebandraos** [taketwo/rs#1]
I'm getting a configuration error when trying to build this which seems to be coming from the RSSDK side of things. The end of cmake (following the instructions to the letter) looks like this...
-- Found RSSDK: C:/Program Files (x86)/Intel/RSSDK/lib/x64/libpxc.lib
-- RealSense SDK found (include: C:/Program Files (x86)/Intel/RSSDK/include, lib
s: optimized;debug)
-- RealSense SDK version: 4.0.0.52526
CMake Warning (dev) at CMakeLists.txt:37 (target_link_libraries):
  Link library type specifier "optimized" is followed by specifier "debug"
  instead of a library name.  The first specifier will be ignored.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:37 (target_link_libraries):
  The "debug" argument must be followed by a library.

-- Configuring incomplete, errors occurred!

The log file shows 0 Warning & 0 Errors for each element up to this point. Any help would be much appreciated.

If I rerun the same cmake command it makes some project files but they then won't build due to missing libraries, I'm guessing, because the configuration was incomplete.

**Comment by taketwo** [comment]
Hi, thanks for reporting. The project configures and builds for me on 64-bit Windows 8 machine. I will try to to do the same on 32-bit virtual machine, perhaps could catch this bug and nail it down. Unfortunately I'm busy until Tuesday, will let you know about my results afterwards.

**Comment by sebandraos** [comment]
Thanks Sergey,
I'm on a 64-bit 8.1 machine, it's just that the RSSDK is under Program Files (x86) with the 64-bit libs by default (assuming that's where 32-bit came from). I'm not familiar with CMake builds so I'm not sure whether I've made things worse in the long run but I've now managed to get this to build by switching the order of FindRSSDK.cmake #Libraries. It seems like the cmake is using RSSDK_LIBRARY and RSSDK_LIBRARY_DEBUG before it's tried to find them. Again I'm not sure if cmake should work in the order it was in originally but mine started working just by moving the first line under #Libraries (set(RSSDK_LIBRARIES optimized...)) to the end (just before #Version). If this a legitimate solution I can commit the edit if you'd like.
(I now have issues with locating procedure entry points to PCLBase but that's almost certainly on my end and I'll try and figure it out)

**Comment by taketwo** [comment]
Sorry for the delay. You correctly identified the problem and the fix. In fact, the order of `set` and `find` instructions was like that before, but then I accidentally shifted the line in 5a2015b. Apparently, I never cleaned CMake cache after that, so did not run into problems. Thanks for bringing this up!

**Comment by sebandraos** [comment]
Cool, glad to know it wasn't a fluke. Just for general feedback/testing purposes as well, I've been messing with this really quite a lot over the past week or two and, other than the memory leak with coloured clouds that you mentioned somewhere, it is really stable and I'm getting 30+fps running on the cpu. Thanks

**Comment by taketwo** [comment]
Thanks for the feedback, great to hear that!

Did you try enabling temporal filtering (median)? The relevant code (lines 226 through 231) is currently commented out in "real_sense_viewer.cpp". Before, I experienced some weird freezes when switching from median filtering to the next option using "k" key. These freezes happen inside the destructor of one of `std::vector`s that belong to the median filter buffer. Strangely enough, currently I do not experience them anymore, though I don't think I changed anything. Would be interesting to know how it  works on your machine.

**Comment by sebandraos** [comment]
Yeah, it stalls for between half a second and 1 second and then runs absolutely fine. There is something particularly odd happening during those freezes actually, my camera seems to turn off (or at least the IR and LEDs turn off)

**Comment by taketwo** [comment]
Hmm, ok, at least it does not freeze to death like it used to before.

**Comment by sebandraos** [comment]
Definitely not

**Comment by taketwo** [comment]
BTW, I've just downloaded a new version of DCM (1.3) from Intel's [website](https://software.intel.com/en-us/intel-realsense-sdk/download). I did some testing and it seems like the memory does not leak anymore!

**Comment by sebandraos** [comment]
As if by magic. I'm definitely not experiencing any memory leaks any more. Thanks for the heads up

**Comment by sebandraos** [comment]
Just tested latest SDK (r3_v5.0.3.187777) and it seems like everything is still stable. Possibly a slight speed increase but impossible to say for sure, temporal filter still flickers between switches, other than that no perceptible changes.

**Comment by taketwo** [comment]
Thanks for reporting!
