### ISSUE TITLE
Work with PCL 1.8.0

### ISSUE THREAD

**Issue by Huehueh** [taketwo/rs#14]
Does it should work with PCL 1.8.0 (VTK version 7.0.0 which seems incompatible)?

**Comment by taketwo** [comment]
This grabber has been merged into upstream PCL and is a part of 1.8.0 release.

**Comment by Huehueh** [comment]
Thank you for answer!

2016-09-16 16:08 GMT+02:00 Sergey Alexandrov notifications@github.com:
