### ISSUE TITLE
How can i use realsense-sdk face-tracking module when using rs_grabber. 

### ISSUE THREAD

**Issue by qwzlh** [taketwo/rs#15]
Hi, i want to use realsense-sdk face-tracking module to get head pose and position when i use rs_grabber to obtain the head point-cloud, but i have no idea how to do it.

**Comment by taketwo** [comment]
Hi, this is outside of the scope of this project. We only provide a point cloud grabber that you can use to get raw data and then pipe to the algorithms found in PCL. If you need to use SDK algorithms, then this grabber is not what you want.
