### ISSUE TITLE
Does this project support vtk8.0 (in PCL 1.8.1)?

### ISSUE THREAD

**Issue by A-suozhang** [taketwo/rs#16]
I finished installing PCL 1.8.1 and it contains vtk 8.0, working well
However while compiling this project 
I meet :

The following configuration files were considered but not accepted:

    C:/Program Files/PCL 1.8.1/3rdParty/VTK/lib/cmake/vtk-8.0/VTKConfig.cmake, version: 8.0.0 (64bit)

**Comment by taketwo** [comment]
This project was merged into upstream PCL. If you are building 1.8.1 from source, then you already have `RealSenseGrabber`.

**Comment by A-suozhang** [comment]
thx so much~ That really solved my probelm
