### ISSUE TITLE
RSSDK Version.

### ISSUE THREAD

**Issue by Ashwinning** [taketwo/rs#6]
Hey Taketwo,

Wanted to ask you which version of RSSDK you were using.

I'm on the latest version (r4_6.0.21.6598 on Windows) and I'm facing some issues. 

First, I noticed that there are no `include` and `lib` folders in the root of the `RSSDK_DIR` directory/folder.

However, there is an `include` folder at `${RSSDK_DIR}/opensource/include`.
There also seems to be an `src` folder at `${RSSDK_DIR}/opensource/src` which looks like this:

```
src
└── libpxc      
 └── libpxc.cpp
```

I changed line 24 in  `FindRSSDK` from `set(RSSDK_INCLUDE_DIRS ${RSSDK_DIR}/include)`
to `set(RSSDK_INCLUDE_DIRS ${RSSDK_DIR}/opensource/include)` to solve some cmake errors, but can't seem to fix the `lib` folder issue in libraries.

Trying to throw in libpxc and libpxc.cpp into a new folder `${RSSDK_DIR}/lib` didn't help.

Here's the error cmake throws: (using CMake 3.3.1)

```
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.3/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find RSSDK (missing: RSSDK_LIBRARIES) (found version
  "6.0.21.6598")
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.3/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindRSSDK.cmake:60 (find_package_handle_standard_args)
  CMakeLists.txt:11 (find_package)
```

And the [CMakeOutput.txt](https://gist.github.com/Ashwinning/f16b4f3368ce86ef1303) in case it might be of any help.

I would appreciate any help possible.

Thanks!

**Comment by sebandraos** [comment]
Hey Ashwin, I think Sergey (TakeTwo) is on Linux so I'll take a pop at answering this. Please can you check where your ${RSSDK} is pointing it should be somewhere along the lines of **C:\Program Files (x86)\Intel\RSSDK**. I am running the same version of the RSSDK and can assure you those folders and libraries are definitely there. I suggest reinstalling the SDK if the path is correct and for future reference lib files should be _.lib_ files, _.cpp_ are the sources.
Let me know if you still have problems after a (clean) reinstall

**Comment by taketwo** [comment]
Hi, I had this migrating from version 5 to version 6. Actually, I was about
to ask you, Sebastian, the same question :D
The solution is to completely uninstall the old version and then make a
fresh clean install of the new one.

**Comment by Ashwinning** [comment]
Hi Sebastian & Sergey,
Thanks for the super quick response guys!

I actually don't see anything for ${RSSDK} anywhere.

I do see`${RSSDK_DIR}` as defined by

```
find_path(RSSDK_DIR include/pxcversion.h
          PATHS "$ENV{RSSDK_DIR}"
                ...
                ...
                )
```

pointing to the correct location (C:\Program Files (x86)\Intel\RSSDK in my case) as the environment variable is set.

I'll try reinstalling the SDK and report back.

Thanks!

**Comment by Ashwinning** [comment]
CMake configured and generated like a charm after the SDK reinstall.
A bit surprising that I was missing the `lib` & `include` folders before.
Thanks for the help guys,
Greatly appreciate it!
