### ISSUE TITLE
Can't run real_sense_viewer.exe

### ISSUE THREAD

**Issue by Ashwinning** [taketwo/rs#7]
Hey guys,
Upon building with VS2015 x64, I'm unable to run `real_sense_viewer.exe`.

On passing the flag `--list`, my R200 shows up correctly, but the nothing seems to happen after the "Creating the grabber" output.

![](https://i.gyazo.com/1b028f193fcc1a511a9e2e69c3675f18.gif)

Will appreciate your guidance.
Thanks!

**Comment by Ashwinning** [comment]
Okay `real_sense_viewer.exe --mode <id>` works. (0, 1, 2, 3 etc..)
I guess the automatic defaulting is not working.

**Comment by taketwo** [comment]
Yeah sorry, that's a bug. Actually the fix is already in the "fix-color" branch. I'll merge it with master soon.

**Comment by Ashwinning** [comment]
Ah cool.
Thank you Sergey!

**Comment by taketwo** [comment]
The fix is in master.
