### ISSUE TITLE
Question : Grabbing and saving points without Visualizing.

### ISSUE THREAD

**Issue by Ashwinning** [taketwo/rs#8]
Hi,

I'm trying to create a CLI/.dll which can grab and save a pointcloud to PCD. For this I do not need to visualize anything.

I was trying to pull it straight from `real_sense_grabber.cpp` to try and hack something together, but it doesn't seem to be working out.

```
//real_sense_grabber.cpp

void
pcl::RealSenseGrabber::run ()
{
  ...
  while (is_running_)
  {
    pcl::PointCloud<pcl::PointXYZ>::Ptr xyz_cloud;
    pcl::PointCloud<pcl::PointXYZRGBA>::Ptr xyzrgba_cloud;

    pxcStatus status;
    ...
    switch (status)
    {
    case PXC_STATUS_NO_ERROR:
    {
     ...

          //Save cloud
      boost::format fmt("RS_%s_%u.pcd");
      std::string fn = boost::str(fmt % getDeviceSerialNumber().c_str() % xyz_cloud->header.stamp);
      pcl::io::savePCDFileBinaryCompressed(fn, *xyz_cloud);

          this->stop(); //Stop running grabber (pcl::RealSenseGrabber::stop())
         break;
    }
    ...
    }
    ...
  }
  ...
}

```

```
//other_script.cpp
...
pcl::RealSenseGrabber grabber (device_id);
grabber.start();
...
```

I was hoping you could guide me towards the correct way of how I should go about achieving this.

Thanks.

**Comment by taketwo** [comment]
I would not recommend to modify grabber sources. The whole idea of having grabbers in PCL is to provide library users with simplified adapters with uniform interface for different SDKs/drivers/cameras. Please look at how the grabber is used in the "real_sense_viewer" application and adapt as needed. Also [this tool](https://github.com/PointCloudLibrary/pcl/blob/master/io/tools/openni_pcd_recorder.cpp) in PCL might be a good example.

**Comment by Ashwinning** [comment]
Ah cool, Thanks!

I was able to create a RealSenseCapture class based on RealSenseViewer with a save() function to save the pointclouds.

Thanks for the example link!

**Comment by taketwo** [comment]
BTW you can save the last grabbed cloud by pressing "s" in the viewer app.
