### ISSUE TITLE
windows has unresolved externals

### ISSUE THREAD

**Issue by martijnvwezel** [taketwo/rs#9]
On a WIN8.1 it has problems with finding real_sensoe.lib, but its made already .. Is that an config error?

**Comment by sebandraos** [comment]
Hey Matijn, Assuming the RealSense SDK is installed you should find the library files at _C:\Program Files (x86)\Intel\RSSDK\lib\ [Win32/x64]_ (by default). If you can find those manually then it is almost certainly a configuration issue.
What is failing to find the libraries? CMake, VisualStudio, Notepad?

**Comment by martijnvwezel** [comment]
yes, when reinstalling the SDK the lib[Win32/x64] was founded! Tanks
